- Dockerfile
The current dockerfile when built comes out to a big 839MB.
I suggest building with alpine instead and it reduces the image to 300MB.
Change line 1 of `dalfox/Dockerfile` to:
```
FROM golang:1.15.2-alpine3.12
```
Unless there are some hard glibc dependencies, I don't see why not. I've tested it and it seems to work fine.
> update docker tag to golang:1.15.2-alpine3.12

- pkg/optimization/optimization.go
Created the PR as discussed in the issue I've opened.
Note that in this way we are **always** adding the Accept header, and I didn't handle the edge case that someone wants to use their own Accept header.
We can handle it by comparing the header value from the options, but since you haven't done it for the `Content-Type` header as well, I thought that we can skip this complication.
BTW, is it only possible to add one header using `-H` or am I missing something here? I saw it while debugging my change.
My change was tested with and wo the `-H` flag.
Please review and merge.
> #174, Add the Accept header to all requests

- pkg/scanning/scan.go
Hey,
In a recent finding we discovered parameters on `form` and `a` tags, which where vulnerable but not discovered by the DOM parameter scanner. I quickly added the possibility to also gather parameters from relative `href` and `action` attributes from `a` and `form` tags.
Feel free to discuss or merge if you like.
> Added DOM based parameter scanning on 'form' and 'a' tags

- cmd/root.go
- go.mod
- go.sum
- pkg/har/client_tracer.go
- pkg/har/har_test.go
- pkg/har/message_id.go
- pkg/har/round_tripper.go
- pkg/har/types.go
- pkg/har/writer.go
- pkg/model/options.go
- pkg/model/result.go
- pkg/optimization/optimization.go
- pkg/scanning/scan.go
- pkg/scanning/sendReq.go
- pkg/scanning/transport.go
Hi,
Here is the draft PR that I mentioned in #439. It is **incomplete and only a draft right now**, but I am sharing it early to get your feedback.
I looked at https://github.com/vvakame/go-harlog and some other packages (I found other packages by going through the results of [this GitHub search](https://github.com/search?q=startedDateTime+language%3AGo&type=code&l=Go)). There were some issues with the other projects that already existed, so I created my own by forking `github.com/vvakame/go-harlog`. Those issues were:
* Their design required that you use one `http.RoundTripper` per HAR archive. Dalfox creates a `http.RoundTripper` in a few different places and I didn't want to make big changes to Dalfox.
* Their design would store the HAR archive in memory and serialize to JSON at the …
> Add HAR file writing support (#439)

- cmd/file.go
- cmd/sxss.go
- cmd/url.go
While I was working around dalfox I encountered an issue which is caused a crash due to no Error handling in the args following the reference below.
How the issue I encountered when I ran it returned the following error in the picture, Not only for the **file** command it's the same for **url** and **sxss**, Even though we don't need to run this but incase user forget to provide the argument they might end up getting stack trace.
```bash
dalfox file
```
https://github.com/hahwul/dalfox/blob/efcef0ffbf0fe775d8722940cce02069d7b51fdb/cmd/file.go#L35
https://github.com/hahwul/dalfox/blob/efcef0ffbf0fe775d8722940cce02069d7b51fdb/cmd/url.go#L15
https://github.com/hahwul/dalfox/blob/efcef0ffbf0fe775d8722940cce02069d7b51fdb/cmd/sxss.go#L18
I checked the code coverage using [github …
> Error handled for index out of range

- docs/_docs/parameter-mining.md
Fixed wrong argument for skipping DOM, before was the same sample from remote wordlists
> Fixed typo on docs

- pkg/har/message_id_test.go
The NewMessageID test in message_id_test.go was updated to check for positive values instead of non-nil values. This change ensures that the generated message ID is a valid positive integer.
> fix: update NewMessageID test to check for positive values

- .github/workflows/codecov.yml
- .github/workflows/go.yml
- docs/page/update.md
- go.mod
- go.sum
Update the Go version to 1.23 in the CI workflows and `go.mod`, while simplifying the installation instructions in the documentation by removing outdated methods.
Signed-off-by: HAHWUL <hahwul@gmail.com>
> Update Go version and installation instructions

- cmd/root.go
- lib/func.go
- lib/func_test.go
- lib/interface.go
- pkg/model/options.go
- pkg/printing/logger.go
- pkg/scanning/scan.go
- pkg/scanning/sendReq.go
- Updated BAV to be disabled by default for improved flexibility.
- Introduced the 'use-bav' option to explicitly enable BAV functionality.
Closed #595
Signed-off-by: HAHWUL <hahwul@gmail.com>
> Change 'BAV' behavior to be disabled by default; add 'use-bav' option to enable it

- pkg/scanning/foundaction.go
I'm encountering a lot of `<defunct>` curl processes when running Dalfox with `--found-action`. The eventual cause my system to crash as they are not cleaned up. This fix cleans up the process resource
> fix: cleanup found action to prevent zombie processes

- docs/Gemfile
- docs/Gemfile.lock
- docs/custom_transport.md
- docs/page/running/code/custom_transport.md
- pkg/model/options.go
- pkg/scanning/transport.go
- pkg/scanning/transport_example.go
- pkg/scanning/transport_test.go
This PR adds support for custom HTTP transports in DalFox, enabling advanced integration with security testing pipelines and enhanced control over HTTP requests.
- **Custom Transport Interface**: Implement support for custom HTTP transports via the `model.Options.CustomTransport` field
- **Transport Chain**: Create chains of transports to apply multiple modifications to requests
- **Header Transport**: Add custom headers to requests
- **Example Implementations**: Include examples for common use cases:
- Custom TLS configuration
- Transport chains
- Retry mechanisms
- OAuth2 authentication
- Rate limiting
- Request/response logging
This feature is particularly valuable for integrating DalFox with other security testing pipelines:
- **HTTP Control Flow**: Customize request handling with …
> Add: Custom transport

- .github/workflows/codecov.yml
Revise the Codecov workflow to utilize the new coverage file format and action for improved reporting.
> Update Codecov workflow for new coverage format and action

- codecov.yml
- go.sum
- pkg/server/scan.go
- pkg/server/server_test.go
Improve error handling during the scan process and implement tests to validate scan functionality and error scenarios.
> Enhance scan error handling and add tests for scan functionality

- cmd/args.go
- cmd/root.go
- pkg/model/options.go
- pkg/scanning/scan.go
Fixes [Skip discovery/analysis · Issue #643 · hahwul/dalfox](https://github.com/hahwul/dalfox/issues/643).
Successfully tested this change on [Lab: Stored XSS into HTML context with nothing encoded | Web Security Academy](https://portswigger.net/web-security/cross-site-scripting/stored/lab-html-context-nothing-encoded):
```
./dalfox sxss https://<LAB>.web-security-academy.net/post/comment \
-X POST \
-H 'Host: <LAB>.web-security-academy.net' \
-H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/133.0.0.0 Safari/537.36' \
-H 'Accept: */*' \
-H 'Content-Type: application/x-www-form-urlencoded' \
-H 'Cookie: session=<SESSION>' \
-d 'comment=example_value&csrf=<CSRF>&email=user%40example.com&name=example_value&postId=10&website=https%3A%2F%2F …
```
> new: add option to skip discovery

- .github/workflows/contributors.yml
Switch the contributors workflow to utilize wow-actions and modify settings to include bots and disable rounding.
> Update contributors workflow to use wow-actions

- .github/workflows/test-functional.yml
- spec/challenges/xss-game.appspot.com/challenge_spec.rb
Modify the functional test workflow to support manual triggering and introduce basic RSpec tests for the XSS game challenge.
> Update functional test workflow and add RSpec tests for XSS challenge

- spec/challenges/testphp.vulnweb.com/challenge_spec.rb
Introduce tests for various endpoints to ensure proper functionality and response handling.
> Add initial tests for endpoints on testphp.vulnweb.com

- cmd/file.go
- cmd/pipe.go
- pkg/model/options.go
Introduce a limit option for the file and pipe commands to control the number of results displayed. This enhancement allows users to specify a maximum number of results, improving usability and performance.
> Add result limit option to file and pipe commands

- README.md
Replace existing badges with updated ones to enhance project visibility and provide better information about releases and contributions.
> Update project badges for improved visibility

- README.md
- pkg/scanning/scan_test.go
- pkg/scanning/transport_example_test.go
Revise the usage of the mock server in Scan tests and enhance test coverage by adding cases for reflected parameters and the `initializeSpinner` function.
> Update Scan tests and mock server usage

- .github/workflows/cd_snapcraft.yml
- snap/snapcraft.yaml
Introduce a Snapcraft configuration to automate the publishing process for Dalfox, including build and release steps for multiple architectures.
> Add Snapcraft configuration for Dalfox publishing

- go.mod
- go.sum
Downgrade the Go version to 1.23.0 and update the volt dependency to version 1.0.7 to ensure compatibility and stability.
> Downgrade Go version and update volt dependency

- pkg/scanning/parameterAnalysis.go
Potential fix for [https://github.com/hahwul/dalfox/security/code-scanning/50](https://github.com/hahwul/dalfox/security/code-scanning/50)
To fix the problem, we need to implement a maximum allowed value for the `concurrency` variable to prevent excessively large allocations. This can be done by adding a check to ensure that the `concurrency` value does not exceed a predefined maximum limit. If the value exceeds the limit, we should set it to the maximum allowed value.
_Suggested fixes powered by Copilot Autofix. Review carefully before merging._
> Potential fix for code scanning alert no. 50: Slice memory allocation with excessive size value

- pkg/server/server.go
- pkg/server/server_test.go
Adds two new API endpoints to the Dalfox server mode:
- DELETE /scans/all: Clears all scan data, including the list of scan IDs and the detailed scan results stored in memory.
- DELETE /scan/:id: Deletes a specific scan by its ID. It removes the ID from the list and deletes the scan details from memory.
Both endpoints return appropriate JSON responses. Swagger annotations have been added for documentation, and unit tests have been implemented to cover success and failure scenarios for these new operations.
> feat: Add DELETE endpoints for scan data management

- cmd/args.go
- cmd/root.go
- docs/page/output-handling.md
- internal/report/report_markdown.go
- internal/report/report_markdown_test.go
- pkg/scanning/scan.go
- Add 'markdown' and 'md' options for --report-format flag
- Implement GenerateMarkdownReport function to generate reports in Markdown format
- Add tests for Markdown report generation
- Update documentation for new report format
> feat: Add markdown report format
